/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.servicebuilder.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Shoe service. Represents a row in the &quot;ShoeServiceBuilder_Shoe&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.servicebuilder.model.impl.ShoeModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.servicebuilder.model.impl.ShoeImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Shoe
 * @generated
 */
@ProviderType
public interface ShoeModel extends BaseModel<Shoe> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a shoe model instance should use the {@link Shoe} interface instead.
	 */

	/**
	 * Returns the primary key of this shoe.
	 *
	 * @return the primary key of this shoe
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this shoe.
	 *
	 * @param primaryKey the primary key of this shoe
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the shoe ID of this shoe.
	 *
	 * @return the shoe ID of this shoe
	 */
	@AutoEscape
	public String getShoeId();

	/**
	 * Sets the shoe ID of this shoe.
	 *
	 * @param shoeId the shoe ID of this shoe
	 */
	public void setShoeId(String shoeId);

	/**
	 * Returns the shoe model of this shoe.
	 *
	 * @return the shoe model of this shoe
	 */
	@AutoEscape
	public String getShoeModel();

	/**
	 * Sets the shoe model of this shoe.
	 *
	 * @param shoeModel the shoe model of this shoe
	 */
	public void setShoeModel(String shoeModel);

	/**
	 * Returns the gender of this shoe.
	 *
	 * @return the gender of this shoe
	 */
	@AutoEscape
	public String getGender();

	/**
	 * Sets the gender of this shoe.
	 *
	 * @param gender the gender of this shoe
	 */
	public void setGender(String gender);

	/**
	 * Returns the size of this shoe.
	 *
	 * @return the size of this shoe
	 */
	public double getSize();

	/**
	 * Sets the size of this shoe.
	 *
	 * @param size the size of this shoe
	 */
	public void setSize(double size);

	/**
	 * Returns the price of this shoe.
	 *
	 * @return the price of this shoe
	 */
	public double getPrice();

	/**
	 * Sets the price of this shoe.
	 *
	 * @param price the price of this shoe
	 */
	public void setPrice(double price);

	/**
	 * Returns the brand ID of this shoe.
	 *
	 * @return the brand ID of this shoe
	 */
	@AutoEscape
	public String getBrandId();

	/**
	 * Sets the brand ID of this shoe.
	 *
	 * @param brandId the brand ID of this shoe
	 */
	public void setBrandId(String brandId);

	/**
	 * Returns the type ID of this shoe.
	 *
	 * @return the type ID of this shoe
	 */
	@AutoEscape
	public String getTypeId();

	/**
	 * Sets the type ID of this shoe.
	 *
	 * @param typeId the type ID of this shoe
	 */
	public void setTypeId(String typeId);

	@Override
	public Shoe cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}