/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.servicebuilder.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Type service. Represents a row in the &quot;ShoeServiceBuilder_Type&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.servicebuilder.model.impl.TypeModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.servicebuilder.model.impl.TypeImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Type
 * @generated
 */
@ProviderType
public interface TypeModel extends BaseModel<Type> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a type model instance should use the {@link Type} interface instead.
	 */

	/**
	 * Returns the primary key of this type.
	 *
	 * @return the primary key of this type
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this type.
	 *
	 * @param primaryKey the primary key of this type
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the type ID of this type.
	 *
	 * @return the type ID of this type
	 */
	@AutoEscape
	public String getTypeId();

	/**
	 * Sets the type ID of this type.
	 *
	 * @param typeId the type ID of this type
	 */
	public void setTypeId(String typeId);

	/**
	 * Returns the name of this type.
	 *
	 * @return the name of this type
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this type.
	 *
	 * @param name the name of this type
	 */
	public void setName(String name);

	@Override
	public Type cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}